[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anydim-metanet"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.1",
    "torchvision>=0.16",
    "torch_geometric>=2.4",
    "einops>=0.7",
    "nfn>=0.1",
    "tqdm",
    "scikit-learn",
    "pyyaml",
    "wandb",
    "mup",
    "numpy",
    "matplotlib",
]

[tool.setuptools.packages.find]
where = ["src"]
