# Plain GMN bidirectional (no scale equivariance) on our generated ReLU INRs (w32).
# Same as gmn_reproduce_sp.yml but with direction: bidirectional.

batch_size: 128
data:
  dataset: labeled_mnist_inr
  dataset_path: $ANYDIM_DATA_ROOT/mnist_inrs/w32_sp/
  split_path: $ANYDIM_DATA_ROOT/mnist_inrs/w32_sp/mnist_splits.json
  image_size: [28,28]
  node_pos_embed: &node_pos_embed True
  edge_pos_embed: &edge_pos_embed True
  layer_layout: [2, 32, 32, 1]

train_args:
  num_epochs: 200
  val_acc_threshold: 0.1
  patience: 50
  seed: 0
  loss: CrossEntropyLoss


scalegmn_args:
  d_in_v: &d_in_v 1
  d_in_e: &d_in_e 1
  d_hid: &d_hid 128
  num_layers: 4
  direction: bidirectional
  equivariant: False
  symmetry: permutation
  jit: False
  compile: False

  readout_range: last_layer
  gnn_skip_connections: True

  concat_mlp_directions: False
  reciprocal: True

  node_pos_embed: *node_pos_embed
  edge_pos_embed: *edge_pos_embed

  graph_init:
    d_in_v: *d_in_v
    d_in_e: *d_in_e
    project_node_feats: True
    project_edge_feats: True
    d_node: *d_hid
    d_edge: *d_hid

  positional_encodings:
    final_linear_pos_embed: False
    sum_pos_enc: True
    po_as_different_linear: False
    equiv_net: False
    sum_on_io: True
    equiv_on_hidden: False
    num_mlps: 3
    layer_equiv_on_hidden: False

  gnn_args:
    d_hid: *d_hid
    message_fn_layers: 1
    message_fn_skip_connections: False
    update_node_feats_fn_layers: 1
    update_node_feats_fn_skip_connections: False
    update_edge_attr: True
    dropout: 0.2
    dropout_all: False
    update_as_act: False
    update_as_act_arg: sum
    mlp_on_io: False

    msg_equiv_on_hidden: False
    upd_equiv_on_hidden: False
    layer_msg_equiv_on_hidden: False
    layer_upd_equiv_on_hidden: False
    msg_num_mlps: 2
    upd_num_mlps: 2
    pos_embed_msg: False
    pos_embed_upd: False
    layer_norm: False
    aggregator: add
    sign_symmetrization: False

  mlp_args:
    d_k: [ *d_hid ]
    activation: silu
    dropout: 0.
    final_activation: identity
    batch_norm: False
    layer_norm: True
    bias: True
    skip: False

  readout_args:
    d_out: 10
    d_rho: *d_hid


optimization:
  clip_grad: True
  clip_grad_max_norm: 10.0
  optimizer_name: AdamW
  optimizer_args:
    lr: 1e-3
    weight_decay: 0.01
  scheduler_args:
    scheduler: WarmupLRScheduler
    warmup_steps: 1000
    scheduler_mode: min
    decay_rate: 0
    decay_steps: 0
    patience: None
    min_lr: None

wandb_args:
  project: mnist_cls
  entity: null
  group: reproduce
  name: gmn-sp-bidir
  tags: [sp, reproduce, permutation, bidirectional]
